### ISSUE TITLE
どこをモジュール化するかだけ考えときませんか

### ISSUE THREAD

**Issue by Colk-tech** [brokenManager/Gorilla-TRPG-suporter#17]

**Comment by isso0424** [comment]
ダイス
PlayerStatusクラス
多分だけどゲームの進行処理も別モジュールの別classで受け持っちゃったほうがいい

**Comment by Colk-tech** [comment]
わかた

**Comment by Colk-tech** [comment]
main.pyでDiscordの入力受け付けてコマンドの種別判定とかはやってあとは呼び出すだけ的な感じ？

**Comment by Colk-tech** [comment]
もちろん簡単なのは別にいいかもしれんけど

**Comment by isso0424** [comment]
そうだね
必要以上の重荷をmain.pyに持たせないようにしよう
結局discordはインターフェースでしか無いからね

**Comment by Colk-tech** [comment]
おけ
